spring:
  application:
     name: vic-ms-productorRabbitMq  # Service registers under this name
  freemarker:
    enabled: false           

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

# HTTP Server
server:
  port: 2001   # HTTP (Tomcat) port

logging:
 level:
  org:
   springframework:
    web: INFO

